# 应用服务 WEB 访问端口
server:
  port: 8080
# 应用名称
spring:
#  application:
#    name: karl-spike-demo
#  mvc:
#    hiddenmethod:
#      filter:
#        enabled: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver # 数据库驱动
    name: defaultDataSource # 数据源名称
    url: jdbc:mysql://localhost:3306/karl-spike?serverTimezone=Asia/Shanghai # 数据库连接地址
    username: 'root' # 数据库用户名&密码
    password: '12345678'
    hikari:
      #连接池名
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接存活最大时间，默认600000
      idle-timeout: 180000
      #最大连接数
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      #连接最大存活时间，0表示永久存活，默认1800000
      max-lifetime: 1800000
      #连接超时时间，默认30秒
      connection-timeout: 30000
      #心跳机制，测试连接是否可用
      connection-test-query: SELECT 1
  # THYMELEAF (ThymeleafAutoConfiguration)
  thymeleaf:
    cache: false # 开启模板缓存（默认值： true ）
    #check-template: true # 检查模板是否存在，然后再呈现
    #check-template-location: true # 检查模板位置是否正确（默认值 :true ）
    #enabled: true # 开启 MVC Thymeleaf 视图解析（默认值： true ）
    encoding: UTF-8 # 模板编码
    #excluded-view-names: '' # 要被排除在解析之外的视图名称列表，⽤逗号分隔
    #mode: HTML
    #prefix: classpath:/templates/ # 在构建 URL 时添加到视图名称前的前缀（默认值： classpath:/templates/ ）
    #suffix: .html # 在构建 URL 时添加到视图名称后的后缀（默认值： .html ）
#    servlet:
#      content-type: text/html

mybatis-plus:
  #配置mapper.xml映射文件
  mapper-locations: classpath*/mapper/*Mapper.xml
  #配置MyBatis数据返回类型别名（默认是类名）
  type-aliases-package: cn.karlguo.spike.pojo

logging:
  level:
    cn.karlguo.spike.mapper: debug

